name: Checkout
on: [push]

jobs:
  checkout-and-disaplay-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -la
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.gh_token }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Lists files after
        run: ls -la