name: Repository Events Types
on: 
  push:
    branches:
      - main
      - "feature/*"  # matches feature/featA feature/featB, but not feature/featA/featB
      - "feature/**" # matches feature/featA/featB
      - "!feature/featA" # doesnot match feature/featA
    #branches-ignore:
    #  - feature/featA
    tags:
      - v1.* # matches v1.1, v1.2
      - "!v1.1.1"
    paths:
      - "**.js"
      - "!app.js"  # exclude a specific java script file app.js for this workflow to run
  pull_request:
    types: [opened, assigned, reopened, synchronize]
    branches:
      - main
    paths:
      - "**.js"
    # it means the workflow will run for the pull requests on the main branch for the java script file
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3