name: Matrix
on: [push]

jobs:
  node-matrix:
    ## prevents to fail the workflow if a job in the matrix fails
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16]
      ## Prevent github to cancel in progress job to fail if a job fails
      fail_fast: false
      ## maximum 3 jobs can run
      ## max-parallel: 3
      runs-on: ${{ matrix.os }}
      steps:
        - run: node -v
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: node -v

