name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        ## you can also use commit id instead of @main, @<commit id>
        with:
          who-to-greet: Ali
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"    
