name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        #run: sleep 20
        run: sleep 90
        timeout-minutes: 1
      - name: Step 2
        id: step-2
        # This will continue to run even if this fails
        # or you can fo timeout-minutes
        continue-on-error: true 
        # This is needed to just check the status of the Step 2
        run: exit 1
        # we explicitly fail to test the failure() condition
      - name: Runs on step 2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        # status check is applied to all if keys by default. 
        # so if we just do steps.step-2.conclusion == 'failure' 
        # then it means success() && steps.step-2.conclusion == 'failure'
        # so we need to check explicitly this
        # failure() && steps.step-2.conclusion == 'failure'
        # we need to overwrite the success() function that is applied by default
        run: echo "Step 2 has failed" 
      - name: Runs on Failure
        if: failure()
        run: echo "Ffailure"
      - name: Runs on Success
        # This is not needed (DEFAULT)
        if: success()
        run: echo "Runs on Success"
      - name: Always Runs
        # if success() || failure ()
        if: always()
        run: echo "Always Runs"
      - name: Runs When Cancelled
        if: cancelled()
        run: echo "Runs on Cancelled"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    # this checks if the job-1 is failed and then execute the following lines
    steps:
      - run: echo 'Job 2'
