name: Calling Reusable workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: 'Ali'
        required: false

jobs:
  calling-a-reusable-wf:
    ## recap  that you should use commit hash, not main
    ## remote workflow syntax from another repo
    # uses: santanu-c/GHworkflows/.github/workflows/reusable.yaml@main
    ## local repo reusable workflow
    uses: ./reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}