name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events Types]
    types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because of 'Repositiory Events Types' was completed